name: Composer updater
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 15 * *'
jobs:
  update-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update composer runner
        id: cup
        uses: kawax/composer-update-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m-%Y')"
      - name: Create pull request
        id: prc
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUBTOKEN }}
          commit-message: Atualizado pacotes do composer
          committer: Github <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: atualizacaoComposer${{ steps.date.outputs.date }}
          delete-branch: true
          title: Atualização do Composer - ${{ steps.date.outputs.date }}
          body: |
            ---

            ## Pacotes atualizados
            ### Validas as alterações

            ---

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            Waiting review
            #talvezvaitercopa