name: Composer updater
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 15 * *'
jobs:
  update-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m-%Y')"
      - name: Update composer runner
        id: cup
        uses: kawax/composer-update-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          APP_SINGLE_BRANCH_POSTFIX: -composer-update-${{ steps.date.outputs.date }}
          GIT_COMMIT_PREFIX: '[AVALIAR] Atualização composer - '